@include('guest.includes.navbar.top_navbar')
@include('guest.includes.navbar.top_sub_navbar')
@include('guest.includes.modal.signin')
@include('guest.includes.modal.signup')
@include('guest.includes.modal.forgot-password')
@include('guest.includes.modal.terms_and_conditions')
@include('guest.includes.modal.privacy_policy')
