# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ stage ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh keys
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRODOERS_HOST }}
        username: ${{ secrets.PRODOERS_USERNAME }}
        key: ${{ secrets.PRODOERS_CPANEL }}
        passphrase: ${{ secrets.PRODOERS_PASSPHRASE }}
#        password:
        port: 22
        script: |
          cd /home/prodoers/public_html/stage
          pwd
          git add .
          git stash --include-untracked
          git pull ${{ secrets.PRODOERS_GITPULL }} stage
          git status

          php artisan cache:delete
          composer install --optimize-autoloader --no-dev
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

